# Generated by Django 5.0.1 on 2024-01-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itsname', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
