# Generated by Django 5.0.1 on 2024-01-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
